# Generated by Django 5.1.4 on 2025-01-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0002_category_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
