# Generated by Django 5.1.4 on 2025-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0003_remove_category_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
